spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/exam
      username: root
      password: 123456


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# jwt配置
jwt:
  header: "Authorization"   # token 返回头部
  tokenPrefix: "Bearer "    # token 前缀
  secret: "yax1n9"          # 签名私钥
  expireTIme: 604800000         # token 有效时间（ms）